### ISSUE TITLE
Suzanne is missing from tutorial11 2d fonts, call the cops!

### ISSUE THREAD

**Issue by cirosantilli** [opengl-tutorials/ogl#15]
https://github.com/opengl-tutorials/ogl/tree/71cad106cefef671907ba7791b28b19fa2cc034d/tutorial11_2d_fonts

The digits render fine, but suzanne is not there as in: http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-11-2d-text/ I only see the blue blackground.

The `suzanne.obj` file contains a line:

    usemtl Material_ray.png
 
but I can't find such file, suspicious.

Ubuntu 15.10.

**Comment by Calvin1602** [comment]
- The material isn't used by the example OBJ loader so it's not related
- My suggestion is that Suzanne is drawn, but you're not looking in the right direction due to the mediocre mouse controls...

I'm closing it just in case, feel free to re-open if you feel it's incorrect. (maybe comment computeMatricesFromInputs() in tutorial11.cpp just to make sure)
