### ISSUE TITLE
All tutorials use VAOs in a very inefficient way

### ISSUE THREAD

**Issue by b-steiner** [opengl-tutorials/ogl#62]
In all tutorials, the VAO setup code (glEnableVertexAttribArray, glVertexAttribPointer) is located inside the main loop although the bindings never change. Even worth, this kind of setup code with enabling/disabling attributes in each frame goes completely against what VAOs are made for and teaches people to issue a lot of unnecessary OpenGL calls.

The better way would be to setup the VAO before the main loop and only use glBindVertexArray with the correct VAO in each frame. (And technically even that would be unnecessary unless there are multiple VAOs/DrawCalls involved).

The problem is not that the solution shown here would be wrong (it actually is valid code) but a lot of people learn writing OpenGL code from your tutorial due to the prominent placement on google. They then later use that code in their own projects and when having a larger number of objects, doing the setup code in each frame will definitely be a problem.

**Comment by Calvin1602** [comment]
Skipping VAOs entirely was a deliberate decision.

First, I have yet to see a bench that makes VAOs more efficient (it may have changed since the tutorials were written).

Secondly, it makes the rendering loop more intuitive - there is one less abstraction layer to understand.

But most importantly, the tutorials were designed to be portable across many OpenGL versions - including OpenGL 2, which still has a important user base on old hardware. It's also not supported in ES until 3.0.

I also chose to re-bind everything each frame because that's closer to what needs to be done in real application, where you can't just assume that only one objects gets drawn.

So, when I finally ditch the 2.1 port (still useful to many people), or if there's a compelling reason to change all the tutorials, I'll update them, but in the meantime, I think it's a good compromise.

**Comment by lax1dude** [comment]
> Skipping VAOs entirely was a deliberate decision.

@Calvin1602 Then why even tell people that its necessary to create that VAO and bind it in the first place? Have you actually read the spec? You don't need to make a VAO there's already a default VAO (0) for backwards compatibility.

> First, I have yet to see a bench that makes VAOs more efficient (it may have changed since the tutorials were written).

I maintain an app that has a VAO based renderer with a backwards compatibility mode for OpenGL contexts with no VAO support, even with an algorithm I painstakingly optimized to avoid enabling/disabling/updating vertex attrib pointers that haven't changed between draws, I still get worse performance when I'm not using VAOs. It doesn't matter if you've never seen VAOs make it faster in your tests, there are probably hundreds of different implementations of OpenGL out there. Of course some shitty integrated laptop graphics from 10 years ago aren't gonna do much differently when you use VAOs, OpenGL is just a standard.

**You need to fix this, or at least clarify that you're intentionally misusing VAOs and people serious about understanding OpenGL shouldn't follow your guide.** Your site is usually the second or third result in Google for "OpenGL Tutorial" so chances are that new developers are being mislead on a daily basis as a result of taking your guide at face value. I know that when I was 13 years old sometime back in 2017 that I followed your guide and took it at face value, and spent at least a year making an ass out of myself misusing VAOs this way until I actually read the spec and saw that vertex attribute pointers are stored per-VAO. Minecraft 1.17 shipped with a renderer that created a discrete VAO for every chunk, but then repeatedly reinitialized each VAO before every draw instead of just initializing each VAO once and I'm willing to bet it was because the developer in charge of porting the game away from the fixed function pipeline read your guide and was mislead by it. This was changed in a later release. Shame.

Please don't brush this under the rug, do the OpenGL community a favor and teach VAOs properly.
